/*
 * games.js
 *
 * Hold data whick is used by renderGames.js
 * classes = all gba flash multi
 */

const games = [
   {
      name: "Fiday Night Funkin' VS Agoti",
      img: "assets/cover-art/friday-night-funkin-vs-agoti.jpg",
      link: "/pages/player.html?src=/friday-night-funkin",
      classes: "all new",
   },
   {
      // done
      name: "007",
      img: "assets/cover-art/007.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23007",
      classes: "all gba",
   },
   {
      // done
      name: "1 on 1 Soccer",
      img: "assets/cover-art/1-on-1-soccer.jpg",
      link: "/pages/player.html?src=/flash/%3Fswf%3D1on1soccer.swf",
      classes: "all multi flash",
   },
   {
      // done
      name: "2048",
      img: "assets/cover-art/2048.jpg",
      link: "/pages/player.html?src=/games/2048/",
      classes: "all",
   },
   {
      // done
      name: "60 Seconds Burger Run",
      img: "assets/cover-art/60-seconds-burger-run.jpg",
      link: "/pages/player.html?src=/games/60sburgerrun/",
      classes: "all",
   },
   {
      // done
      name: "8 Ball Pool",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/8ball/",
      classes: "all multi",
   },
   {
      // done
      name: "A Dark Room",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/a-dark-room/",
      classes: "all",
   },
   {
      // done
      name: "Advance Wars",
      img: "assets/cover-art/advance-wars.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23advancewars",
      classes: "all gba",
   },
   {
      // done
      name: "Advance Wars 2: Black Hole Rising",
      img: "assets/cover-art/advance-wars-2.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23advancewars2",
      classes: "all gba",
   },
   {
      // done
      name: "Adventure Capitalist",
      img: "assets/cover-art/adventure-capitalist.jpg",
      link: "/pages/player.html?src=/games/adventure-capitalist/",
      classes: "all",
   },
   {
      // done
      name: "Age of War",
      img: "assets/cover-art/age-of-war.jpg",
      link: "/pages/player.html?src=/flash/%3Fswf%3Dageofwar.swf",
      classes: "all flash",
   },
   {
      // done
      name: "Alien Hominid",
      img: "assets/cover-art/alien-hominid.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23alienhominid",
      classes: "all gba",
   },
   {
      // done
      name: "Atari Anniversary Advance",
      img: "assets/cover-art/atari-anniversary-advance.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23atari",
      classes: "all gba",
   },
   {
      // done
      name: "Bad Ice-Cream",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/badicecream/",
      classes: "all multi",
   },
   {
      // done
      name: "Bad Ice-Cream 2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/badicecream2/",
      classes: "all multi",
   },
   {
      // done
      name: "Bad Ice-Cream 3",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/badicecream3/",
      classes: "all multi",
   },
   {
      // done
      name: "Basket Random",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/basket-random/",
      classes: "all multi",
   },
   {
      // done
      name: "Basketball Stars",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/basketball-stars/",
      classes: "all multi sport",
   },
   {
      // done
      name: "Big Tower Tiny Square",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/btts/",
      classes: "all",
   },
   {
      // done
      name: "BitLife",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/bitlife/",
      classes: "all",
   },
   {
      // done
      name: "Black Hole Square",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/black-hole-square/",
      classes: "all",
   },
   {
      name: "Bloons Tower Defense 1",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=bloonstd1.swf",
      classes: "all flash",
   },
   {
      name: "Bloons Tower Defense 2",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=bloonstd2.swf",
      classes: "all flash",
   },
   {
      name: "Bloxorz",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=bloxorz.swf",
      classes: "all flash",
   },
   {
      name: "Bomberman Max 2: Blue Advance",
      img: "assets/cover-art/bomberman-max-2.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23bomberman_max2blue",
      classes: "all gba",
   },
   {
      name: "Bomberman Tournament",
      img: "assets/cover-art/bomberman-tournament.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23bomberman_tournament",
      classes: "all gba",
   },
   {
      name: "Bounce Back",
      img: "assets/place-holder.jpg",
      link: "games/bounce-back/",
      classes: "all",
   },
   {
      name: "Boxing Random",
      img: "assets/place-holder.jpg",
      link: "/games/boxing-random/",
      classes: "all multi",
   },
   {
      name: "Bullet Bill",
      img: "assets/cover-art/bullet-bill.jpg",
      link: "games/flash/?swf=bulletbill.swf",
      classes: "all flash",
   },
   {
      name: "Cell Machine",
      img: "assets/place-holder.jpg",
      link: "games/cell-machine/",
      classes: "all",
   },
   {
      // done
      name: "Chess",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/chess/",
      classes: "all multi",
   },
   {
      name: "Choppy Orc",
      img: "assets/place-holder.jpg",
      link: "games/choppyorc/docs/",
      classes: "all edd",
   },
   {
      // done
      name: "Chrome Dinosaur",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/chrome-dino/",
      classes: "all",
   },
   {
      name: "CircloO",
      img: "assets/place-holder.jpg",
      link: "/games/circloo/",
      classes: "all",
   },
   {
      name: "Clicker Heroes",
      img: "assets/place-holder.jpg",
      link: "/games/clickerheroes/",
      classes: "all  ",
   },
   {
      // done
      name: "Cookie Clicker",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/games/cookie-clicker/",
      classes: "all",
   },
   {
      name: "Craftmine",
      img: "assets/place-holder.jpg",
      link: "games/craftmine/",
      classes: "all",
   },
   {
      // done
      name: "Crash Bandicoot 2: N-Tranced",
      img: "assets/cover-art/crash-bandicoot-2.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23cb2",
      classes: "all gba",
   },
   {
      // done
      name: "Crash Bandicoot: The Huge Adventure",
      img: "assets/cover-art/crash-bandicoot-huge-adventure.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23cbha",
      classes: "all gba",
   },
   {
      // done
      name: "Crash Bandicoot: Ripto's Rampage",
      img: "assets/cover-art/crash-bandicoot-ripto-rampage.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23cbprr",
      classes: "all gba",
   },
   {
      // done
      name: "Connect Four / Perfection / Trouble",
      img: "assets/cover-art/connect-four-perfection-trouble.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23cfpt",
      classes: "all gba",
   },
   {
      // done
      name: "Crash Nitro Kart",
      img: "assets/cover-art/crash-nitro-kart.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23cnk",
      classes: "all gba",
   },
   {
      // done
      name: "Croket! Yume no Banker Survival!",
      img: "assets/cover-art/croket!-yume-no-banker-survival!.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23croket1",
      classes: "all gba",
   },
   {
      // done
      name: "Croket! 2: Yami no Bank to Ban Joou",
      img: "assets/cover-art/croket!-2-yami-no-bank-to-ban-joou.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23croket2",
      classes: "all gba",
   },
   {
      // done
      name: "Croket! 3: Granyuu Oukoku no Nazo",
      img: "assets/cover-art/croket!-3-granyuu-oukoku-no-nazo.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23croket3",
      classes: "all gba",
   },
   {
      // done
      name: "Croket! 4: Bank no Mori no Mamorigami",
      img: "assets/cover-art/croket!-4-bank-no-mori-no-mamorigami.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23croket4",
      classes: "all gba",
   },
   {
      name: "Cube Field",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=cubefield.swf",
      classes: "all flash",
   },
   {
      name: "Cut The Rope",
      img: "assets/place-holder.jpg",
      link: "games/ctr/",
      classes: "all",
   },
   {
      name: "Cut The Rope Holiday Gift",
      img: "assets/place-holder.jpg",
      link: "games/ctr-holiday/",
      classes: "all",
   },
   {
      name: "Cut The Rope Time Travel",
      img: "assets/place-holder.jpg",
      link: "games/ctr-tr/",
      classes: "all",
   },
   {
      name: "Death Run 3D",
      img: "assets/place-holder.jpg",
      link: "games/death-run-3d/",
      classes: "all",
   },
   {
      name: "Duke Nukem Advance",
      img: "assets/cover-art/duke-nukem-advance.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23dna",
      classes: "all gba",
   },
   {
      name: "Digimon Racing",
      img: "assets/cover-art/digimon-racing.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23digimon_racing",
      classes: "all gba",
   },
   {
      name: "Dr. Mario / Puzzle League",
      img: "assets/cover-art/dr-mario-puzzle-league.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23dmpl",
      classes: "all gba",
   },
   {
      name: "Donkey Kong Country",
      img: "assets/cover-art/donkey-kong-country.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23dkc",
      classes: "all gba",
   },
   {
      name: "Donkey Kong Country 2: Diddy's Kong Quest",
      img: "assets/cover-art/donkey-kong-country-2-diddy-kong-quest.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23dkc2",
      classes: "all gba",
   },
   {
      name: "Donkey Kong Country 3: Dixie Kong's Double Trouble!",
      img: "assets/cover-art/donkey-kong-country-3-dixie-kongs-double-trouble!.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23dkc3",
      classes: "all gba",
   },
   {
      name: "DK: King of Swing",
      img: "assets/cover-art/dk-king-of-swing.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23dkkos",
      classes: "all gba",
   },
   {
      name: "Doodle Jump",
      img: "assets/place-holder.jpg",
      link: "games/doodle-jump/",
      classes: "all",
   },
   {
      name: "Doom",
      img: "assets/cover-art/doom.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23dm",
      classes: "all gba",
   },
   {
      name: "Doom II",
      img: "assets/cover-art/doom-ii.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23dm2",
      classes: "all gba",
   },
   {
      name: "Dragon Ball Z: Supersonic Warriors",
      img: "assets/cover-art/dragon-ball-z-supersonic-warriors.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23dbz_supersonic",
      classes: "all gba",
   },
   {
      name: "Draw The Hill",
      img: "assets/place-holder.jpg",
      link: "games/draw-the-hill/",
      classes: "all",
   },
   {
      name: "Drill Dozer",
      img: "assets/cover-art/drill-dozer.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23drilldozer",
      classes: "all gba",
   },
   {
      name: "Duck Life",
      img: "assets/cover-art/duck-life.jpg",
      link: "games/flash/?swf=ducklife.swf",
      classes: "all flash",
   },
   {
      name: "Duck Life 2",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=ducklife2.swf",
      classes: "all flash",
   },
   {
      name: "Duck Life 3",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=ducklife3.swf",
      classes: "all flash",
   },
   {
      name: "Duck Life 4",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=ducklife4.swf",
      classes: "all flash",
   },
   {
      name: "Dungeons & Dragons: Eye of the Beholder",
      img: "assets/cover-art/dungeons-and-dragons-eye-of-the-beholder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23dnd",
      classes: "all gba",
   },
   {
      name: "Earthworm Jim",
      img: "assets/cover-art/earthworm-jim.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23earthwormjim",
      classes: "all gba",
   },
   {
      name: "Earthworm Jim 2",
      img: "assets/cover-art/earthworm-jim-2.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23earthwormjim_m2",
      classes: "all gba",
   },
   {
      name: "Pokemon Emerald Version",
      img: "assets/cover-art/pokemon-emerald-version.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23eprp",
      classes: "all gba",
   },
   {
      name: "Edge Not Found",
      img: "assets/place-holder.jpg",
      link: "games/edgenotfound/",
      classes: "all",
   },
   {
      name: "Escaping the Prison",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=escapingtheprison.swf",
      classes: "all flash",
   },
   {
      name: "Evil Glitch",
      img: "assets/place-holder.jpg",
      link: "games/evilglitch/",
      classes: "all",
   },
   {
      name: "F-Zero: GP Legend",
      img: "assets/cover-art/f-zero-gp-legend.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23fzero_gp",
      classes: "all gba",
   },
   {
      name: "F-Zero: Maximum Velocity",
      img: "assets/cover-art/f-zero-maximum-velocity.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23fzero_max",
      classes: "all gba",
   },
   {
      name: "Factory Balls",
      img: "assets/place-holder.jpg",
      link: "games/factoryballs/",
      classes: "all",
   },
   {
      name: "Family Feud",
      img: "assets/cover-art/family-feud.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23ffeud",
      classes: "all gba",
   },
   {
      name: "Fantastic 4",
      img: "assets/cover-art/fantastic-4.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23fan4",
      classes: "all gba",
   },
   {
      name: "Fantastic 4: Flame On",
      img: "assets/cover-art/fantastic-4-flame-on.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23fan4fo",
      classes: "all gba",
   },
   {
      name: "FIFA Football 2004",
      img: "assets/cover-art/fifa-football-2004.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23fifa4",
      classes: "all gba",
   },
   {
      name: "FIFA Football 2005",
      img: "assets/cover-art/fifa-football-2005.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23fifa5",
      classes: "all gba",
   },
   {
      name: "FIFA Football 2006",
      img: "assets/cover-art/fifa-football-2006.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23fifa6",
      classes: "all gba",
   },
   {
      name: "FIFA Football 2007",
      img: "assets/cover-art/fifa-football-2007.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23fifa7",
      classes: "all gba",
   },
   {
      name: "FIFA World Cup 2006",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23ffafwc6",
      classes: "all gba",
   },
   {
      name: "Final Fantasy I & II: Dawn of Souls",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23ff1and2",
      classes: "all gba",
   },
   {
      name: "Final Fantasy IV (S)",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23ff4S",
      classes: "all gba",
   },
   {
      name: "Final Fantasy Tactics Advance",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23final_fantasy_tactics",
      classes: "all gba",
   },
   {
      name: "Final Fantasy VI Advance",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23ff6",
      classes: "all gba",
   },
   {
      name: "Fire Emblem",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23fire_emblem",
      classes: "all gba",
   },
   {
      name: "fireboy watergirl 1",
      img: "assets/place-holder.jpg",
      link: "games/fbwg/",
      classes: "all",
   },
   {
      name: "fireboy watergirl 2",
      img: "assets/place-holder.jpg",
      link: "games/fbwg2/",
      classes: "all",
   },
   {
      name: "fireboy watergirl 3",
      img: "assets/place-holder.jpg",
      link: "games/fbwg3/",
      classes: "all",
   },
   {
      name: "fireboy watergirl 4",
      img: "assets/place-holder.jpg",
      link: "games/fbwg4/",
      classes: "all",
   },
   {
      name: "Flappy Bird",
      img: "assets/place-holder.jpg",
      link: "games/flappybird/",
      classes: "all",
   },
   {
      name: "Flappy Squidward",
      img: "assets/place-holder.jpg",
      link: "games/flappySquidward/",
      classes: "all",
   },
   {
      name: "Friendly Fire",
      img: "assets/place-holder.jpg",
      link: "/games/friendlyfire/",
      classes: "all  ",
   },
   {
      name: "Frogger 2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23frogger2",
      classes: "all gba",
   },
   {
      name: "Frogger's Adventures 3",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23fr3",
      classes: "all gba",
   },
   {
      name: "Frogger's Adventures: Temple of the Frog",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23frogger1",
      classes: "all gba",
   },
   {
      name: "Frogger's Journey: The Forgotten Relic",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23frogger3",
      classes: "all gba",
   },
   {
      name: "Funny Shooter 2",
      img: "assets/place-holder.jpg",
      link: "/games/funnyshooter2/",
      classes: "all  ",
   },
   {
      name: "Pokemon: Gaia",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23gaia",
      classes: "all gba",
   },
   {
      name: "Game & Watch Gallery 4",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23gamewatch4",
      classes: "all gba",
   },
   {
      name: "Game Inside A Game",
      img: "assets/place-holder.jpg",
      link: "games/game-inside/",
      classes: "all",
   },
   {
      name: "Pokemon Video 1",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23gba_video_pokemon_1",
      classes: "all gba",
   },
   {
      name: "Pokemon Video 2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23gba_video_pokemon_2",
      classes: "all gba",
   },
   {
      name: "Pokemon Video 3",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23gba_video_pokemon_3",
      classes: "all gba",
   },
   {
      name: "Pokemon Video 4",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23gba_video_pokemon_4",
      classes: "all gba",
   },
   {
      name: "Getaway Shooter",
      img: "assets/place-holder.jpg",
      link: "games/getaway-shootout/",
      classes: "all multi",
   },
   {
      name: "Golden Sun",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23goldensun",
      classes: "all gba",
   },
   {
      name: "Google Snake",
      img: "assets/place-holder.jpg",
      link: "games/google-snake/",
      classes: "all",
   },
   {
      name: "Google Solitaire",
      img: "assets/place-holder.jpg",
      link: "/games/google-solitaire/",
      classes: "all  ",
   },
   {
      name: "Grand Theft Auto",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23gta",
      classes: "all gba",
   },
   {
      name: "GunBlood",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=gunblood.swf",
      classes: "all flash",
   },
   {
      name: "Gunstar Super Heroes",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23gunstar_super_heroes",
      classes: "all gba",
   },
   {
      name: "Hamtaro Ham-Ham Heartbreak",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23hamtaro_heartbreak",
      classes: "all gba",
   },
   {
      name: "Harvest Moon: Friends of Mineral Town",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23hmfmt",
      classes: "all gba",
   },
   {
      name: "Harvest Moon: More Friends of Mineral Town",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23hmmfmt",
      classes: "all gba",
   },
   {
      name: "Hobo 1",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=hobo.swf",
      classes: "all flash",
   },
   {
      name: "Hobo 2: Prison Brawl",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=hobo2.swf",
      classes: "all flash",
   },
   {
      name: "Hobo 3: Wanted",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=hobo3.swf",
      classes: "all flash",
   },
   {
      name: "Hobo 4: Total War",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=hobo4.swf",
      classes: "all flash",
   },
   {
      name: "Hobo 5: Space Brawl",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=hobo5.swf",
      classes: "all flash",
   },
   {
      name: "Hobo 6: Hell",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=hobo6.swf",
      classes: "all flash",
   },
   {
      name: "Hobo 7: Heaven",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=hobo7.swf",
      classes: "all flash",
   },
   {
      name: "Idle Breakout",
      img: "assets/place-holder.jpg",
      link: "games/idle-breakout/",
      classes: "all",
   },
   {
      name: "Iridion 3D",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23iridion",
      classes: "all gba",
   },
   {
      name: "007: Nightfire",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23jbn",
      classes: "all gba",
   },
   {
      name: "Jackie Chan: Legend of the Dark Hand",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23jca",
      classes: "all gba",
   },
   {
      name: "Jelly Mario",
      img: "assets/place-holder.jpg",
      link: "games/jelly-mario/jellymar/",
      classes: "all",
   },
   {
      name: "Jlc",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23jlc",
      classes: "all gba",
   },
   {
      name: "Jlifa",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23jlifa",
      classes: "all gba",
   },
   {
      name: "Jlthb",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23jlthb",
      classes: "all gba",
   },
   {
      name: "Jp3Dna",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23jp3dna",
      classes: "all gba",
   },
   {
      name: "Jp3Ia",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23jp3ia",
      classes: "all gba",
   },
   {
      name: "Jp3Pb",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23jp3pb",
      classes: "all gba",
   },
   {
      name: "Khcom",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23khcom",
      classes: "all gba",
   },
   {
      name: "Kirbymirror",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23kirbymirror",
      classes: "all gba",
   },
   {
      name: "Kirbynightmare",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23kirbynightmare",
      classes: "all gba",
   },
   {
      name: "Lb",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23lb",
      classes: "all gba",
   },
   {
      name: "Li2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23li2",
      classes: "all gba",
   },
   {
      name: "Lotr2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23lotr2",
      classes: "all gba",
   },
   {
      name: "Lotr3",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23lotr3",
      classes: "all gba",
   },
   {
      name: "Lotrtta",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23lotrtta",
      classes: "all gba",
   },
   {
      name: "Lr2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23lr2",
      classes: "all gba",
   },
   {
      name: "Lsw",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23lsw",
      classes: "all gba",
   },
   {
      name: "Lyp",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23lyp",
      classes: "all gba",
   },
   {
      name: "M3",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23m3",
      classes: "all gba",
   },
   {
      name: "Madalin Stunt Cars",
      img: "assets/place-holder.jpg",
      link: "games/madalin-cars-multiplayer/",
      classes: "all",
   },
   {
      name: "Mario Kart",
      img: "assets/place-holder.jpg",
      link: "games/gba/launcher.html#mariokart",
      classes: "all gba",
   },
   {
      name: "Mariokart",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23mariokart",
      classes: "all gba",
   },
   {
      name: "Marioland",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23marioland",
      classes: "all gba",
   },
   {
      name: "Marioparty",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23marioparty",
      classes: "all gba",
   },
   {
      name: "Mariopinball",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23mariopinball",
      classes: "all gba",
   },
   {
      name: "Meat Boy",
      img: "assets/cover-art/meat-boy.jpg",
      link: "/pages/player.html?src=/flash/%3Fswf%3Dmeatboy.swf",
      classes: "all flash",
   },
   {
      name: "Megaman Battle1",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23megaman_battle1",
      classes: "all gba",
   },
   {
      name: "Megaman Battle2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23megaman_battle2",
      classes: "all gba",
   },
   {
      name: "Megaman Battle3 Blue",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23megaman_battle3_blue",
      classes: "all gba",
   },
   {
      name: "Megaman Battle4 Blue",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23megaman_battle4_blue",
      classes: "all gba",
   },
   {
      name: "Megaman Battle4 Red",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23megaman_battle4_red",
      classes: "all gba",
   },
   {
      name: "Megaman Battle5",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23megaman_battle5",
      classes: "all gba",
   },
   {
      name: "Megaman Battle6",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23megaman_battle6",
      classes: "all gba",
   },
   {
      name: "Megaman Zero1",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23megaman_zero1",
      classes: "all gba",
   },
   {
      name: "Megaman Zero2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23megaman_zero2",
      classes: "all gba",
   },
   {
      name: "Megaman Zero3",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23megaman_zero3",
      classes: "all gba",
   },
   {
      name: "Megaman Zero4",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23megaman_zero4",
      classes: "all gba",
   },
   {
      name: "Megamanbass",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23megamanbass",
      classes: "all gba",
   },
   {
      name: "Metalslug",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23metalslug",
      classes: "all gba",
   },
   {
      name: "Metroid Fusion",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23metroid_fusion",
      classes: "all gba",
   },
   {
      name: "Miami Shark",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=miamishark.swf",
      classes: "all flash",
   },
   {
      name: "Mindustry",
      img: "assets/place-holder.jpg",
      link: "games/mindustry/",
      classes: "all",
   },
   {
      name: "Minecraft 1.8.8",
      img: "assets/cover-art/minecraft.jpg",
      link: "minecraft/",
      classes: "all multi",
   },
   {
      name: "Minecraft Classic",
      img: "assets/place-holder.jpg",
      link: "games/mc-classic/",
      classes: "all",
   },
   {
      name: "Minekhan",
      img: "assets/place-holder.jpg",
      link: "games/minekhan/",
      classes: "all",
   },
   {
      name: "Mini Putt",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=miniputt.swf",
      classes: "all flash",
   },
   {
      name: "Momotarou Dentetsu",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23momotarou_dentetsu",
      classes: "all gba",
   },
   {
      name: "Monopoly",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23monopoly",
      classes: "all gba multi",
   },
   {
      name: "Monster Force",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23monster_force",
      classes: "all gba",
   },
   {
      name: "Mortal Kombat",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23mortal_kombat",
      classes: "all gba",
   },
   {
      name: "Moto X3M",
      img: "assets/place-holder.jpg",
      link: "games/motox3m/",
      classes: "all",
   },
   {
      name: "Moto X3M Pool Party",
      img: "assets/place-holder.jpg",
      link: "games/motox3m-pool/",
      classes: "all",
   },
   {
      name: "Moto X3M Spooky Land",
      img: "assets/place-holder.jpg",
      link: "games/motox3m-spooky/",
      classes: "all",
   },
   {
      name: "Moto X3M Winter",
      img: "assets/place-holder.jpg",
      link: "games/motox3m-winter/",
      classes: "all",
   },
   {
      name: "Ms Pacman",
      img: "assets/place-holder.jpg",
      link: "games/pacman/",
      classes: "all",
   },
   {
      name: "Mvsdk",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23mvsdk",
      classes: "all gba",
   },
   {
      name: "Mysteryred",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23mysteryred",
      classes: "all gba",
   },
   {
      name: "Mzm",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23mzm",
      classes: "all gba",
   },
   {
      name: "Nbaj",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23nbaj",
      classes: "all gba",
   },
   {
      name: "Nesgh1",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23nesgh1",
      classes: "all gba",
   },
   {
      name: "Nfrp",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23nfrp",
      classes: "all gba",
   },
   {
      name: "Nfsu",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23nfsu",
      classes: "all gba",
   },
   {
      name: "Nfsu2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23nfsu2",
      classes: "all gba",
   },
   {
      name: "Onepiece",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23onepiece",
      classes: "all gba",
   },
   {
      name: "Pacman World",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pacman_world",
      classes: "all gba",
   },
   {
      name: "Pacman World2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pacman_world2",
      classes: "all gba",
   },
   {
      name: "Papa's Pizzeria",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=papaspizzeria.swf",
      classes: "all flash",
   },
   {
      name: "Paper.io 2",
      img: "assets/place-holder.jpg",
      link: "games/paperio2/",
      classes: "all",
   },
   {
      name: "Pmc",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pmc",
      classes: "all gba",
   },
   {
      name: "Pmpa",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pmpa",
      classes: "all gba",
   },
   {
      name: "Pokemon Ek",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pokemon_ek",
      classes: "all gba",
   },
   {
      name: "Pokemon Emerald",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pokemon_emerald",
      classes: "all gba",
   },
   {
      name: "Pokemon Florsky",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pokemon_florsky",
      classes: "all gba",
   },
   {
      name: "Pokemon Ruby",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pokemon_ruby",
      classes: "all gba",
   },
   {
      name: "Pokemongb",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pokemongb",
      classes: "all gba",
   },
   {
      name: "Pokemongreen",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pokemongreen",
      classes: "all gba",
   },
   {
      name: "Pokemonlp",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pokemonlp",
      classes: "all gba",
   },
   {
      name: "Pokemonred",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pokemonred",
      classes: "all gba",
   },
   {
      name: "Pokemonsapphire",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pokemonsapphire",
      classes: "all gba",
   },
   {
      name: "Pokewb",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pokewb",
      classes: "all gba",
   },
   {
      name: "Ppf",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23ppf",
      classes: "all gba",
   },
   {
      name: "Pprs",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23pprs",
      classes: "all gba",
   },
   {
      name: "Prs",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23prs",
      classes: "all gba",
   },
   {
      name: "Pushback",
      img: "assets/place-holder.jpg",
      link: "games/pushback/",
      classes: "all",
   },
   {
      name: "Puyopop",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23puyopop",
      classes: "all gba",
   },
   {
      name: "R3Hh",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23r3hh",
      classes: "all gba",
   },
   {
      name: "Ra",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23ra",
      classes: "all gba",
   },
   {
      name: "Retro Bowl",
      img: "assets/place-holder.jpg",
      link: "/games/retro-bowl/",
      classes: "  all",
   },
   {
      name: "Rooftop Snipers",
      img: "assets/place-holder.jpg",
      link: "games/rooftop-snipers/",
      classes: "all multi",
   },
   {
      name: "Rsrs",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23rsrs",
      classes: "all gba",
   },
   {
      name: "Rtpl",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23rtpl",
      classes: "all gba",
   },
   {
      name: "Run 3",
      img: "assets/place-holder.jpg",
      link: "run3/",
      classes: "all",
   },
   {
      name: "Sag",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23sag",
      classes: "all gba",
   },
   {
      name: "Sans Fight",
      img: "assets/place-holder.jpg",
      link: "games/sans-fight/",
      classes: "all",
   },
   {
      name: "Sc",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23sc",
      classes: "all gba",
   },
   {
      name: "Simpsons",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23simpsons",
      classes: "all gba",
   },
   {
      name: "Sims Bustin Out",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23sims_bustin_out",
      classes: "all gba",
   },
   {
      name: "Sims2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23sims2",
      classes: "all gba",
   },
   {
      name: "Slope",
      img: "assets/place-holder.jpg",
      link: "games/slope/",
      classes: "all",
   },
   {
      name: "Sma4",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23sma4",
      classes: "all gba",
   },
   {
      name: "Soccer Random",
      img: "assets/place-holder.jpg",
      link: "/games/soccer-random/",
      classes: "all multi",
   },
   {
      name: "Soldier Legend",
      img: "assets/place-holder.jpg",
      link: "games/soldier-legend/",
      classes: "all",
   },
   {
      name: "Sonic Advance",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23sonic_advance",
      classes: "all gba",
   },
   {
      name: "Sonic Advance2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23sonic_advance2",
      classes: "all gba",
   },
   {
      name: "Sonic Advance3",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23sonic_advance3",
      classes: "all gba",
   },
   {
      name: "Sonicbattle",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23sonicbattle",
      classes: "all gba",
   },
   {
      name: "Sonicpinball",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23sonicpinball",
      classes: "all gba",
   },
   {
      name: "Sort The Court",
      img: "assets/place-holder.jpg",
      link: "games/sort-the-court/",
      classes: "all",
   },
   {
      name: "Spelunky",
      img: "assets/place-holder.jpg",
      link: "spelunky/",
      classes: "all",
   },
   {
      name: "Spyro Adventure",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23spyro_adventure",
      classes: "all gba",
   },
   {
      name: "Spyro Flame",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23spyro_flame",
      classes: "all gba",
   },
   {
      name: "Spyro Ice",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23spyro_ice",
      classes: "all gba",
   },
   {
      name: "Stealing the Diamond",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=stealingthediamond.swf",
      classes: "all flash",
   },
   {
      name: "Sthg",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23sthg",
      classes: "all gba",
   },
   {
      name: "Stick Slasher",
      img: "assets/place-holder.jpg",
      link: "games/stickslasher/",
      classes: "all",
   },
   {
      name: "Subway Surfers",
      img: "assets/place-holder.jpg",
      link: "games/subway-surfers/",
      classes: "all",
   },
   {
      name: "Super Mario 64",
      img: "assets/place-holder.jpg",
      link: "games/sm64/",
      classes: "all",
   },
   {
      name: "Super Mario Bros",
      img: "assets/place-holder.jpg",
      link: "games/full-screen-mario/",
      classes: "all",
   },
   {
      name: "Super Street Fighter 2 Turbo",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23super_street_fighter_2_turbo",
      classes: "all gba",
   },
   {
      name: "Super Street Fighter 3 Alpha",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23super_street_fighter_3_alpha",
      classes: "all gba",
   },
   {
      name: "Superhot Prototype",
      img: "assets/place-holder.jpg",
      link: "games/superhot/",
      classes: "all",
   },
   {
      name: "Supermariodvance",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23supermariodvance",
      classes: "all gba",
   },
   {
      name: "Supermariodvance2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23supermariodvance2",
      classes: "all gba",
   },
   {
      name: "Supermariodvance3",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23supermariodvance3",
      classes: "all gba",
   },
   {
      name: "Supermariodvance4",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23supermariodvance4",
      classes: "all gba",
   },
   {
      name: "Supermonkeyballjr",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23supermonkeyballjr",
      classes: "all gba",
   },
   {
      name: "Superstar",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23superstar",
      classes: "all gba",
   },
   {
      name: "Swerve",
      img: "assets/place-holder.jpg",
      link: "games/swerve/",
      classes: "all",
   },
   {
      name: "Tak2 Staff Of Dreams",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23tak2_staff_of_dreams",
      classes: "all gba",
   },
   {
      name: "Tales Of Phantasia",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23tales_of_phantasia",
      classes: "all gba",
   },
   {
      name: "Tank Trouble 2",
      img: "assets/place-holder.jpg",
      link: "games/tank-trouble-2/",
      classes: "all multi",
   },
   {
      name: "Tanuki Sunset",
      img: "assets/place-holder.jpg",
      link: "games/tanuki-sunset/",
      classes: "all",
   },
   {
      name: "Temple Run 2",
      img: "assets/place-holder.jpg",
      link: "games/temple-run-2/",
      classes: "all",
   },
   {
      name: "Tetra Legends",
      img: "assets/place-holder.jpg",
      link: "games/tetra-legends/",
      classes: "all",
   },
   {
      name: "Tetris",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=tetris.swf",
      classes: "all flash",
   },
   {
      name: "Tetris Worlds",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23tetris_worlds",
      classes: "all gba",
   },
   {
      name: "Tggtc",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23tggtc",
      classes: "all gba",
   },
   {
      name: "Tgr",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23tgr",
      classes: "all gba",
   },
   {
      name: "Thas",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23thas",
      classes: "all gba",
   },
   {
      name: "The Worlds Hardest Game",
      img: "assets/place-holder.jpg",
      link: "games/worlds-hardest-game/",
      classes: "all",
   },
   {
      name: "The Worlds Hardest Game 2",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=worldshardestgame2.swf",
      classes: "all flash",
   },
   {
      name: "There Is No Game",
      img: "assets/place-holder.jpg",
      link: "games/there-is-no-game/",
      classes: "all",
   },
   {
      name: "Thps2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23thps2",
      classes: "all gba",
   },
   {
      name: "Thps3",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23thps3",
      classes: "all gba",
   },
   {
      name: "Thps4",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23thps4",
      classes: "all gba",
   },
   {
      name: "Thu",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23thu",
      classes: "all gba",
   },
   {
      name: "Thu2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23thu2",
      classes: "all gba",
   },
   {
      name: "Tiny Fishing",
      img: "assets/place-holder.jpg",
      link: "games/tinyfishing/",
      classes: "all",
   },
   {
      name: "Tmnt",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23tmnt",
      classes: "all gba",
   },
   {
      name: "Toss The Turtle",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=tosstheturtle.swf",
      classes: "all flash",
   },
   {
      name: "Townscaper",
      img: "assets/place-holder.jpg",
      link: "games/townscaper/",
      classes: "all",
   },
   {
      name: "Tube Jumpers",
      img: "assets/place-holder.jpg",
      link: "games/tube-jumpers/",
      classes: "all multi",
   },
   {
      name: "Turok Evolution",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23turok_evolution",
      classes: "all gba",
   },
   {
      name: "Ty2",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23ty2",
      classes: "all gba",
   },
   {
      name: "Ty3",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23ty3",
      classes: "all gba",
   },
   {
      name: "Unfair Mario",
      img: "assets/place-holder.jpg",
      link: "games/flash/?swf=unfairmario.swf",
      classes: "all flash",
   },
   {
      name: "Unsb",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23unsb",
      classes: "all gba",
   },
   {
      name: "Vex 3",
      img: "assets/place-holder.jpg",
      link: "games/vex3/",
      classes: "all",
   },
   {
      name: "Vex 4",
      img: "assets/place-holder.jpg",
      link: "games/vex4/",
      classes: "all",
   },
   {
      name: "Vex 5",
      img: "assets/place-holder.jpg",
      link: "games/vex5/",
      classes: "all",
   },
   {
      name: "Vex 6",
      img: "assets/place-holder.jpg",
      link: "games/vex6/",
      classes: "all",
   },
   {
      name: "Vex 7",
      img: "assets/place-holder.jpg",
      link: "games/vex7/",
      classes: "all  ",
   },
   {
      name: "Volley Random",
      img: "assets/place-holder.jpg",
      link: "/games/volley-random/",
      classes: "all multi",
   },
   {
      name: "Wario Ware",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23wario_ware",
      classes: "all gba",
   },
   {
      name: "Warioland4",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23warioland4",
      classes: "all gba",
   },
   {
      name: "Winter Falling",
      img: "assets/place-holder.jpg",
      link: "/games/winter-falling/",
      classes: "all  ",
   },
   {
      name: "Wordle+",
      img: "assets/place-holder.jpg",
      link: "games/wordle/",
      classes: "all",
   },
   {
      name: "Ynfa",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23ynfa",
      classes: "all gba",
   },
   {
      name: "Zelda Minish",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23zelda_minish",
      classes: "all gba",
   },
   {
      name: "Zelda Past",
      img: "assets/place-holder.jpg",
      link: "/pages/player.html?src=/gba/launcher.html%23zelda_past",
      classes: "all gba",
   },
];